In [20]:
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
data = np.load("lcdm_dm_structure_formation.npz")

In [5]:
for key in data.keys():
  print(key)

dm_z
dm_pos

In [30]:
timezero = pd.DataFrame(data['dm_pos'][:,0,:])
timezero

              0            1            2
0    484.613617  1488.219971   163.826859
1     12.550520   372.080017   139.760757
2     25.570118   439.175232   206.379272
3     39.034218   507.721466   273.575073
4     52.830418   577.235657   341.600159
5     66.877586   647.557129   410.544495
6   1006.004089   346.890228    32.748890
7   1016.949036   434.039978   100.962395
8   1027.944336   521.825806   169.715103
9   1039.025757   610.075256   238.879089
10  1050.184937   698.858276   308.518005
11   353.558594    71.734680   743.706177
12   371.590332   173.396667   836.587830
13   389.177460   275.303406   929.981812
14   406.307617   377.516327  1023.971375
15    76.513611  2221.176025   513.968811
16  1531.833496  2036.216553   474.944427
17    28.774933  1460.731323   947.579712
18    62.178268  1554.082764  1054.821777
19   214.228195  1111.109985    31.346819
20   265.094818  1225.249023   138.968597
21   315.430023  1339.550903   247.040054
22   365.233948  1454.011108   355.587616
23   414.395844  1568.402344   464.445984
24   462.964355  1682.849365   573.833008
25   510.894867  1797.308350   683.762817
26   558.087341  1911.577759   794.089355
27  1086.929810    34.040916   647.803528
28   650.128235  2139.390381  1015.874329
29   751.097229    91.850372   849.285095
30   782.521179   231.207138  1000.105042
31   543.661316   373.052094    89.354538
32   569.683289   528.441040   250.721817
33   595.375366   683.196899   412.006134
34   620.657043   836.818176   572.666382
35   645.582581   990.139587   733.735352
36   419.824066  1961.833618   631.635193
37   457.933960  2098.121582   775.245483
38   495.507355  2233.481689   918.965332
39  1033.645020    67.247826  1072.046143
40  1966.972656  1736.226440  1980.891602
41  1950.710327  1876.698120  2106.633789
42   650.636597  1783.730225    61.293221
43   677.418274  1932.916016   209.377274
44   704.316284  2081.212646   357.229187
45   731.225159  2228.099121   504.305664
46  1154.481445  1044.622192  2186.799072
47   799.408508   158.874512  4507.075195
48   997.183960   824.515808   100.348465
49  1025.900757   954.737549   238.049103

In [45]:
#ax = Axes3D(fig)
angleA = 10
angleB = 11
for index2 in range(0,100):
    timezero = pd.DataFrame(data['dm_pos'][:,index2,:])
    
    #1#
    fig = plt.figure(figsize=(10,7))
    ax = fig.add_subplot(111, projection='3d')
    ax.view_init(33, angleA)
    ax.set_axis_off()
    ax.set_zlim(-5000, 5000)
    ax.set_ylim(-5000, 5000)
    ax.set_xlim(-5000, 5000)
    for index in range(0, 50):
        ax.scatter(timezero.iloc[index][0], timezero.iloc[index][1], timezero.iloc[index][2], c='r', marker='^')

    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')

    #plt.show()
    plt.savefig("pics_sc1\pic" + str(index2) + ".png")
    plt.close('all')
    
    #2#
    
    fig = plt.figure(figsize=(10,7))
    ax = fig.add_subplot(111, projection='3d')
    ax.view_init(33, angleB)
    ax.set_axis_off()
    ax.set_zlim(-5000, 5000)
    ax.set_ylim(-5000, 5000)
    ax.set_xlim(-5000, 5000)
    for index in range(0, 50):
        ax.scatter(timezero.iloc[index][0], timezero.iloc[index][1], timezero.iloc[index][2], c='r', marker='^')

    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')

    #plt.show()
    plt.savefig("pics_sc2\pic" + str(index2) + ".png")
    plt.close('all')